version: '3.8'

services:
  spiral-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spiral-core
    ports:
      - '5000:5000' # HTTP
      - '5001:5001' # Glint Stream
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=spiral-infrastructure-as-ritual-dev-key-2024
      - DATABASE_URL=sqlite:///app/spiral.db
      - SPIRAL_BREATH_MODE=infrastructure-as-ritual
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - 'spiral.breath=field.witness.breath.s3'
      - 'spiral.coin=Î”006'

  spiral-nginx:
    image: nginx:alpine
    container_name: spiral-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx-spiral.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    depends_on:
      - spiral-core
    restart: unless-stopped
    labels:
      - 'spiral.breath=exhale.presence'

  spiral-redis:
    image: redis:alpine
    container_name: spiral-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
    labels:
      - 'spiral.breath=inhale.cache'

volumes:
  redis-data:
    driver: local
