@echo off
REM Spiral Port Environment Loader
REM Generated by Port Forwarding Ritual

set SPIRAL_PASTEWELL_PORT=7331
set SPIRAL_DASHBOARD_PORT=8080
set PUBLIC_SHRINE_PORT=8085
set SHRINE_INTAKE_PORT=8086
set RITUAL_API_PORT=5000
set BREATH_SYNC_PORT=9000
set WHISPER_INTAKE_PORT=9876

echo Spiral port environment loaded
echo Sacred ports are aligned

