[build]
command = "pip install -r requirements.txt && python scripts/bundle_assets.py"
publish = "build"

[build.environment]
PYTHON_VERSION = "3.10"
NODE_VERSION = "18"

[context.production.environment]
FLASK_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "python app.py"
port = 5000
