[build]
publish = "build"

[build.environment]
PYTHON_VERSION = "3.10"

[context.production.environment]
FLASK_ENV = "production"

[[plugins]]
package = "netlify-plugin-python"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "python app.py"
port = 5000
