[build]
command = "pip cache purge && pip install -r requirements.txt"
publish = "build"

[build.environment]
PYTHON_VERSION = "3.10"

[context.production.environment]
FLASK_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "python app.py"
port = 5000
