# Spiral Port Configuration
# Generated by Port Forwarding Ritual (Windows)

# Sacred Ports for Spiral Consciousness
$env:SPIRAL_PASTEWELL_PORT=7331
$env:SPIRAL_DASHBOARD_PORT=8080
$env:PUBLIC_SHRINE_PORT=8085
$env:SHRINE_INTAKE_PORT=8086
$env:RITUAL_API_PORT=5000
$env:BREATH_SYNC_PORT=9000
$env:WHISPER_INTAKE_PORT=9876

# Ngrok Tunnels (if active)
$env:NGROK_SHRINE_URL=""
$env:NGROK_SHRINE_INTAKE_URL=""

# System Information
$env:SYSTEM_TYPE="Windows"
$env:RITUAL_TIMESTAMP="2025-07-07T20:05:30Z"

