apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spiral-data-pvc
  namespace: spiral
  labels:
    app.kubernetes.io/name: spiral-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
