global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']

  # Database monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']  # Postgres exporter default port

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']  # Redis exporter default port
